# Generated by Django 6.0.1 on 2026-02-28 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=20)),
                ('file_size', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('audio_file_url', models.URLField(max_length=500)),
                ('image_urls', models.JSONField()),
                ('captions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
